blog/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDeleteView
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('Users/', include('users.urls')),
    path('FaceID/', include('FaceID.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('editProfile/', user_views.editProfile, name='editProfile'),
    path('FaceIDLogin/', user_views.faceIDLogin, name='FaceIDLogin'),
    path('FaceIDLoginSuccess/', user_views.faceIDLoginSuccess, name='FaceIDLoginSuccess'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class post(models.Model):
    title = models.CharField(max_length=100, default="  ")
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content  # print out title of objects instead of number of objects returned

    def get_absolute_url(self):
        return reverse('blog-home')

blog/views.py
from django.shortcuts import render
from .models import post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    post_list = post.objects.all().order_by('-date_posted')
    page = request.GET.get('page', 1)

    paginator = Paginator(post_list, 10)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts  # pass in posts dict to 'posts' key in context dict
    }

    return render(request, 'blog/home.html', context)  # pass in the context dict


class PostListView(ListView):  # <app>/<model>_<Viewtype>.html
    model = post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 10  # number of posts per page


class PostCreateView(LoginRequiredMixin, CreateView):
    model = post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type ="text/css" href="{% static 'blog/main.css' %}">


    {% if title %}
        <title>Django Blog - {{title}}</title>
      {% else %}
        <title>Django Blog</title>
      {% endif %}</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
          <a class="nav-item nav-link" href="/about">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
          <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

    <main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/blog/base_old.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type ="text/css" href="{% static 'blog/main.css' %}">


    {% if title %}
        <title>Django Blog - {{title}}</title>
      {% else %}
        <title>Django Blog</title>
      {% endif %}</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
          <a class="nav-item nav-link" href="/about">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
          <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

    <main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/blog/home.html
{% extends "base.html" %}




{% block content %}

    <div class="main-container">

<header class="header-6">
    <div class="branding">
        <a href="/"> <img class="brand-logo" src= 'media/vmware-white.png'  width="184" height="60" }} ></a>
    </div>
    <div class="header-nav">

        <a href='/' class="active nav-link nav-text">Home</a>
        {% if user.is_authenticated %}
            <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
            <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
            <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

        {% else %}
            <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
            <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
        {% endif %}

    </div>
    <div class="header-actions">
        <a href="javascript://" class="nav-link nav-icon" aria-label="settings">
            <clr-icon shape="cog"></clr-icon>
        </a>
    </div>
</header>

    <div class="content-container">
        <div class="content-area">

    <h2 style="text-align: left"><br>Feedback</h2>
    {% if not user.is_authenticated %}
        Thank you for visiting VMware EBC <br>
        If you would like to leave a feedback please <a href="/login/">log in</a> or <a href="/register/">register</a>
    {% endif %}

    {% for post in posts %}


                <div class="card">
            <div class="card-block">
                <div class="card-media-block">
                    <img src="{{ post.author.profile.image.url }}" width="50" height="50">
                    <div class="card-media-description">
                        <span class="card-media-title">
                            {{ post.author }}
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                        </span>
                        <div class="row">
                          <div class="column">
                        {% if post.title == '1' %}
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        {% elif post.title == '2' %}
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        {% elif post.title == '3' %}
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        {% elif post.title == '4' %}
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-line.svg" width="15" height="15">
                        {% elif post.title == '5' %}
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        <img src="static/media/star-solid.svg" width="15" height="15">
                        {% endif %}
                          </div>
                        </div>
                    </div>
                </div>
                <div class="card-text">
                 <p class="article-content">{{ post.content }}</p>
                </div>
            </div>
                {% if post.author == user %}
            <div class="card-footer">
            <a href="{% url 'post-update' post.id %}"><img src="static/media/pencil-line.svg" width="15" height="15"></a>
            <a href="{% url 'post-delete' post.id %}"><img src="static/media/trash-line.svg" width="15" height="15"></a>
            </div>
                {% endif %}
        </div>




    {% endfor %}
    <br>
    {% if posts.has_other_pages %}

        <clr-dg-footer>
    <clr-dg-pagination>
        {% if posts.has_previous %}
          <a href="?page={{ posts.previous_page_number }}"> < </a>
        {% else %}
       <span> < </span>
        {% endif %}
        {% for i in posts.paginator.page_range %}
          {% if posts.number == i %}
              <a><b>{{ i }}</b></a>
          {% else %}
            <a href="?page={{ i }}">{{ i }}</a>
          {% endif %}
        {% endfor %}
        {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}"> > </a>
        {% else %}
          <span> > </span>
        {% endif %}
    {% endif %}
    <br>
  </clr-dg-pagination>
</clr-dg-footer>
        </div>
        <nav class="sidenav">
        <section class="sidenav-content">
            <a href="https://www.vmware.com/sg/products.html" class="nav-link">
                View our products
            </a>
            <a href="https://www.vmware.com/sg/company/customers.html#" class="nav-link">
                Customer success stories
            </a>
        </section>
        </nav>
    </div>
</div>

{% endblock content %}

templates/blog/post_confirm_delete.html
{% extends "base.html"%}
{% load static %}
{%block content%}
        <div class="main-container">
    <header class="header-6">
        <div class="branding">
            <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
        </div>
        <div class="header-nav">

            <a href='/' class="nav-link nav-text">Home</a>
            {% if user.is_authenticated %}
                <a class="active nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
                <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

            {% else %}
                <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
                <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
            {% endif %}

        </div>

    </header>
  <div class="content-container">
        <div class="content-area">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <h2>Are you sure you want to delete the post "{{ object.content }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-danger-outline" type="submit">Yes, Delete</button>
        <a class ="btn btn-outline" href="{% url 'blog-home' %}">Cancel</a>
      </div>
    </form>
  </div>
  </div>
        </div>
{% endblock content%}

templates/blog/post_form.html
{% extends "base.html"%}
{% load static %}
{%block content%}
    <div class="main-container">
    <header class="header-6">
        <div class="branding">
            <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
        </div>
        <div class="header-nav">

            <a href='/' class="nav-link nav-text">Home</a>
            {% if user.is_authenticated %}
                <a class="active nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
                <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

            {% else %}
                <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
                <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
            {% endif %}

        </div>

    </header>

    <br>
<div class="content-container">
        <div class="content-area">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <h3>Feedback Form</h3><br>
        How would you rate your VMware EBC Experience? (1 being Very Unsatisfied, 5 being Very Satisfied)<br>
          <!-- <textarea name="title" cols="40" rows="1" required="" id="id_title"></textarea> -->
          <input type="radio" id="rating1" name="title" value="1">
          <label for="1">1</label>
          <input type="radio" id="rating2" name="title" value="2">
          <label for="2">2</label>
          <input type="radio" id="rating3" name="title" value="3">
          <label for="3">3</label>
          <input type="radio" id="rating4" name="title" value="4">
          <label for="4">4</label>
          <input type="radio" id="rating5" name="title" value="5">
          <label for="5">5</label><br>
          <br>
          How do you think your VMware EBC experience can be improved?<br>
          <textarea name="content" cols="40" rows="5" required="" id="id_content"></textarea>
      </fieldset>
      <div class="form-group">
        <button class ="btn btn-outline-info" type="submit">Post</button>
      </div>
    </form>
  </div>
</div>

    </div>
{% endblock content%}