blog/urls.py
from django.urls import path
from .views import PostCreateView, PostUpdateView, PostDeleteView
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('Users/', include('users.urls')),
    path('FaceID/', include('FaceID.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('editProfile/', user_views.editProfile, name='editProfile'),
    path('FaceIDLogin/', user_views.faceIDLogin, name='FaceIDLogin'),
    path('FaceIDLoginSuccess/', user_views.faceIDLoginSuccess, name='FaceIDLoginSuccess'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

urlpatterns = (

)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user, filename)


class Profile(models.Model):
    fc = models.BooleanField(default=False)  # Enable FaceID
    fc_setup = models.BooleanField(default=False)  # if FaceID has been set up or not
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username}''s Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class FcPic(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    pic = models.ImageField(null=True, upload_to='face_images')

    def __str__(self):
        return f'{self.profile.user.username}'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    fc = forms.BooleanField(required=False, label='Enable FaceID')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'fc']

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = '<small>Your password can’t be too similar to your other personal ' \
                                             'information.<br>Your password must contain at least 8 ' \
                                             'characters.<br>Your password can’t be a commonly used password.<br>Your ' \
                                             'password can’t be entirely numeric. <br><br></small> '
        for fieldname in ['username', 'password2']:
            self.fields[fieldname].help_text = None


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        help_texts = {'username': (None)}
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class FacialRecForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['fc']


class PasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)

users/views.py
import os
import pickle
import time
import cv2
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from urllib.parse import urlencode
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, FacialRecForm, PasswordForm
from .models import Profile
from django.contrib.auth.models import User
from my_project.settings import MEDIA_ROOT


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(username=username, password=raw_password)
            login(request, account)
            if form.cleaned_data['fc']:
                return redirect('setup')

            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('profile')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    user = request.user
    context = {
        'user': user
    }

    return render(request, 'users/profile.html', context)


def editProfile(request):
    checked = Profile.objects.get(user=request.user).fc
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        f_form = FacialRecForm(request.POST, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            f_form.save()
            messages.success(request, f'Your account has been updated!')

            if Profile.objects.get(user=request.user).fc and not Profile.objects.get(user=request.user).fc_setup:
                return redirect('setup')

            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        f_form = FacialRecForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'f_form': f_form,
        'checked': checked,
    }

    return render(request, 'users/EditProfile.html', context)


def faceIDLogin(request):
    if request.method == 'POST' and 'start' in request.POST:
        userID = recognize()

        if userID is None:
            return render(request, 'users/FaceIDLogin.html', {'message': 'No camera detected'})

        if userID >= 0:
            base_url = reverse('FaceIDLoginSuccess')
            user = User.objects.get(id=userID).username
            query_string = urlencode({'username': user})
            url = '{}?{}'.format(base_url, query_string)
            return redirect(url)

        elif userID == -1:
            return render(request, 'users/FaceIDLogin.html', {'message': 'We are having difficulties detecting your '
                                                                         'face, press to try again.'})

        elif userID == -2:
            return render(request, 'users/FaceIDLogin.html', {'message': 'One face at a time please.'})

    return render(request, 'users/FaceIDLogin.html')


def faceIDLoginSuccess(request):
    if request.method == 'POST':
        form = PasswordForm(request.POST)
        if form.is_valid():
            raw_password = form.cleaned_data['password']
            username = request.GET.get('username')

            account = authenticate(username=username, password=raw_password)
            if account is not None:
                login(request, account)
                return redirect('profile')

    form = PasswordForm()
    return render(request, 'users/FaceIDLoginSuccess', {'form': form})


def recognize():
    face_cascade = cv2.CascadeClassifier(
         '/Users/benjaminchen/Desktop/my_project/venv/lib/python3.8/site-packages/cv2/data/haarcascade_frontalface_alt2.xml'
        #'/usr/local/lib/python3.7/dist-packages/cv2/data/haarcascade_frontalface_alt2.xml'
    )

    trainerPath = os.path.join(MEDIA_ROOT, "trainer.yml")

    if not os.path.exists(trainerPath):
        return None

    recognizer = cv2.face.LBPHFaceRecognizer_create()

    recognizer.read(trainerPath)

    labelsPath = os.path.join(MEDIA_ROOT, "labels.pickle")

    with open(labelsPath, 'rb') as f:
        og_labels = pickle.load(f)
        labels = {v: k for k, v in og_labels.items()}

    cap = cv2.VideoCapture(0)
    if cap is None or not cap.isOpened():
        return None
    def make_480p():
        cap.set(3, 640)
        cap.set(4, 480)

    make_480p()

    timeout = time.time() + 20  # 20 seconds from now
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.5, minNeighbors=3)
        if len(faces) > 1:
            return -2
        for (x, y, w, h) in faces:
            roi_gray = gray[y:y + h, x:x + w]
            id_, conf = recognizer.predict(roi_gray)
            if 45 <= conf <= 85:
                userID = labels[id_]
                # font = cv2.FONT_HERSHEY_SIMPLEX
                # color = (255, 255, 255)
                # stroke = 2
                # cv2.putText(frame, userID, (x, y), font, 1, color, stroke, cv2.LINE_AA)
                return int(userID)

            # color = (255, 0, 0)  # BGR
            # stroke = 2
            # cv2.rectangle(frame, (x, y), (w + x, h + y), color, stroke)

        # cv2.imshow('frame', frame)


        if time.time() > timeout:
            return -1

templates/users/EditProfile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>
  <style>
    .fishes
    {
      position:absolute;
        left: 22%;
        top: 60px;
        right: 0px;
        width: auto;
      z-index: 0;
        border-radius: 2%;
    }
    .fish
    {
        position: absolute;
        left: 23%;
        top: 300px;
        border-radius: 50%;
      z-index: 2;
    }
  </style>
</head>

<div class="main-container" >
    <header class="header-6">
    <div class="branding" >
        <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
    </div>
    <div class="header-nav">

        <a href='/' class="nav-link nav-text">Home</a>
        {% if user.is_authenticated %}
            <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
            <a class="active nav-link nav-text" href="{% url 'profile' %}">Profile</a>
            <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

        {% else %}
            <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
            <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
        {% endif %}

    </div>

    </header>

    <div class="content-container">
        <div class="content-area">
        <div class="login-wrapper">
<form method="POST" class="login" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="title">
        <h3 class="welcome">Edit Profile</h3>
    </section>
  <fieldset class="form-group">
      {{ u_form.as_p }}
      {{ p_form.as_p }}
    <label>
        {% if checked %}
            <input type="checkbox" id="id_fc" name="fc" checked="checked">
        {% else %}
            <input type="checkbox" id="id_fc" name="fc">
        {% endif %}
      <span for="id_fc">Enable Face ID</span>
    </label>

  </fieldset>
  <div class="form-group">
      <button class="btn btn-primary" type="submit">Update</button>
  </div>
</form>
        </div>
   </div>

    <nav class="sidenav">
        <section class="sidenav-content">
            <a href={% url 'profile' %} class="nav-link">
                Profile
            </a>
            <a href={% url 'editProfile' %} class="active nav-link">
                Edit Profile
            </a>
            <a href="#" class="nav-link">
                Posts
            </a>
        </section>
    </nav>

</div>
{% endblock content %}

templates/users/FaceIDLogin.html
 {% extends "base.html" %}
{% load static %}
 {% block content %}
    <div class="main-container">
    <header class="header-6">
        <div class="branding">
            <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
        </div>
        <div class="header-nav">

            <a href='/' class="nav-link nav-text">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
                <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

            {% else %}
                <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
                <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
            {% endif %}

        </div>

    </header>

    <div class="content-container">
        <div class="content-area">
     <h1>Face ID Login</h1>
         <br>
         <h5> Face the camera and press start.</h5>
        <br>
     <form method="post">
         {% csrf_token %}
         {% if message %}
        <button type="submit" name="start"  class="btn btn-primary">Try again</button>
             {% else %}
        <button type="submit" name="start"  class="btn btn-primary">Start</button>
         {% endif %}
     </form>

     {% if message %}
        {{ message }}
     {% endif %}

     </div>
    </div>
    </div>
{% endblock content%}

templates/users/FaceIDsetupSuccess.html
{% extends "base.html" %}
{% load static %}
 {% block content %}
     <div class="main-container">
    <header class="header-6">
                <div class="branding">
            <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
        </div>
        <div class="header-nav">

            <a href='/' class="nav-link nav-text">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
                <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

            {% else %}
                <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
                <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
            {% endif %}

        </div>

    </header>
<div class="content-container">
        <div class="content-area">
    <div class="alert alert-success" role="alert">
        <div class="alert-items">
            <div class="alert-item static">
                <div class="alert-icon-wrapper">
                    <clr-icon class="alert-icon" shape="check-circle"></clr-icon>
                </div>
                <span class="alert-text">
                    Face ID has been setup successfully
                </span>
            </div>
        </div>
    </div>
     <h1>Face ID Setup</h1>
     <br>
        <br>
        <br>
        Progress: 100%
         <div class="progress-static">
                    <div class="progress-meter" data-value="100"></div>
            </div>
        <br>
     {% for pic in pics %}
     <img src="{{  pic.pic.url }}" width="256" height="192">
     {% endfor %}
     </div>
</div>
     </div>

{% endblock content%}

templates/users/login.html
{% extends "base.html" %}
{% load static %}
{%block content%}

    <header class="header-6">
<div class="branding">
    <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
</div>
<div class="header-nav">

    <a href='/' class="nav-link nav-text">Home</a>
    {% if user.is_authenticated %}
        <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
        <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
        <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

    {% else %}
        <a href="{% url 'login' %}" class="active nav-link nav-text">Login</a>
        <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
    {% endif %}

</div>
<div class="header-actions">
    <a href="javascript://" class="nav-link nav-icon" aria-label="settings">
        <clr-icon shape="cog"></clr-icon>
    </a>
</div>
</header>



    <div class="login-wrapper">
    <form class="login" method="post">
        {% csrf_token %}
        <section class="title">
            <h3 class="welcome">Welcome to</h3>
            VMware EBC
            <h5 class="hint">Sign in or create an account now</h5>
        </section>
        {{ form }}
        <br>
         <button class="btn btn-primary" type="submit">Login</button>
         <a href="{% url 'FaceIDLogin' %}" class="waves-effect waves-light btn">Login with Face ID</a>
        <small class="text-muted ml-2">
          <a href="{% url 'password_reset' %}">Forgot Password</a>
        </small>
        <small class="text-muted">
        Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
      </small>
    </form>

</div>







{% endblock content%}

templates/users/logout.html
{% extends "base.html" %}
{% load static %}
{%block content%}
 <div class="main-container">
<header class="header-6">
<div class="branding">
    <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
</div>
<div class="header-nav">

    <a href='/' class="nav-link nav-text">Home</a>
    {% if user.is_authenticated %}
        <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
        <a class="active nav-link nav-text" href="{% url 'profile' %}">Profile</a>
        <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

    {% else %}
        <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
        <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
    {% endif %}

</div>

</header>
<br>

   <div class="content-container">
        <div class="content-area">
<h4>You have been logged out </h4>
<div class="border-top pt-3">
  <small class="text-muted">
    <a href="{% url 'login' %}">Log in Again </a>
  </small>
</div>
    </div>
   </div>
 </div>
{% endblock content%}

templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{%block content%}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class ="btn btn-outline-info" type="submit">Request Password Reset</button>
      </div>
    </form>
  </div>
{% endblock content%}

templates/users/password_reset_complete.html
{% extends "base.html" %}
{%block content%}
<div class="alert alert-info">
  Your password has been set.
</div>
<a href="{% url 'login' %}">Login Now</a>
{% endblock content%}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{%block content%}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class ="btn btn-outline-info" type="submit">Reset Password</button>
      </div>
    </form>
  </div>
{% endblock content%}

templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{%block content%}
<div class="alert alert-info">
  An email has been sent with instructions to reset your password
</div>
{% endblock content%}

templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>
  <style>
    .fishes
    {
      position:absolute;
        left: 22%;
        top: 60px;
        right: 0px;
        width: auto;
      z-index: 0;
        border-radius: 2%;
    }
    .fish
    {
        position: absolute;
        left: 23%;
        top: 300px;
        border-radius: 50%;
      z-index: 2;
    }
  </style>
</head>

<div class="main-container" >
    <header class="header-6">
    <div class="branding" >
        <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
    </div>
    <div class="header-nav">

        <a href='/' class="nav-link nav-text">Home</a>
        {% if user.is_authenticated %}
            <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
            <a class="active nav-link nav-text" href="{% url 'profile' %}">Profile</a>
            <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

        {% else %}
            <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
            <a href="{% url 'register' %}" class="nav-link nav-text"> Register</a>
        {% endif %}

    </div>

    </header>

    <div class="content-container">
        <div class="content-area">
         <img src="{{ user.profile.image.url }}" class="fish" width="140" height="140">
        <img src={% static 'media/vmware.jpg' %} class="fishes" height="400">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    <h1> <img src={% static 'media/user-line.svg' %}> {{ user.username }}</h1>
    <h3> Name: {{ user.first_name }} {{ user.last_name }}</h3>
    <h3> Email: {{ user.email }}</h3>
    </div>

    <nav class="sidenav">
        <section class="sidenav-content">
            <a href={% url 'profile' %} class="nav-link active">
                Profile
            </a>
            <a href={% url 'editProfile' %} class="nav-link">
                Edit Profile
            </a>
            <a href="#" class="nav-link">
                Posts
            </a>
        </section>
    </nav>

    </div>
</div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}
{% load static %}
{%block content%}
        <header class="header-6">
        <div class="branding">
            <a href="/"> <img class="brand-logo" src= "{% static 'media/vmware-white.png' %}"  width="184" height="60" }} ></a>
        </div>
        <div class="header-nav">

            <a href='/' class="nav-link nav-text">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-link nav-text" href="{% url 'post-create' %}">Feedback</a>
                <a class="nav-link nav-text" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link nav-text" href="{% url 'logout' %}">Logout</a>

            {% else %}
                <a href="{% url 'login' %}" class="nav-link nav-text">Login</a>
                <a href="{% url 'register' %}" class="active nav-link nav-text"> Register</a>
            {% endif %}

        </div>
        <div class="header-actions">
            <a href="javascript://" class="nav-link nav-icon" aria-label="settings">
                <clr-icon shape="cog"></clr-icon>
            </a>
        </div>
    </header>


        <div class="login-wrapper">
    <form class="login" method="post">
        {% csrf_token %}
        <section class="title">
            <h3 class="welcome">Welcome to</h3>
            VMware EBC
            <h5 class="hint">Registration Form</h5>
        </section>
        <br>
        {{ form }}
        <br>
         <button class="btn btn-primary" type="submit">Sign up</button>
        <small class="text-muted">
        Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In </a>
      </small>
    </form>

</div>




<br>


{% endblock content%}